package com.modolus.processor;

import com.modolus.util.result.Result;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeSpec;
import lombok.Getter;
import org.jetbrains.annotations.NotNull;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Element;
import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public final class SourceFileWriter {

    @Getter
    private final TypeSpec.Builder classBuilder;

    private final Element root;
    private final String packageName;
    private final MethodSpec.Builder constructorBuilder;
    private final List<MethodSpec> methods;
    private final List<FieldSpec> fields;

    public SourceFileWriter(@NotNull Element root,
                            @NotNull String packageName,
                            @NotNull String className) {
        this.root = root;
        this.packageName = packageName;
        this.classBuilder = TypeSpec.classBuilder(className);
        this.constructorBuilder = MethodSpec.constructorBuilder().addModifiers(Modifier.PROTECTED);
        this.methods = new ArrayList<>();
        this.fields = new ArrayList<>();
    }

    public MethodSpec.Builder getConstructor() {
        return this.constructorBuilder;
    }

    public void addField(FieldSpec field) {
        this.fields.add(field);
    }

    public void addMethod(MethodSpec method) {
        this.methods.add(method);
    }

    public @NotNull Result<Void, ProcessorException> write(@NotNull ProcessingEnvironment processingEnvironment) {
        var clazz = classBuilder
                .addFields(this.fields)
                .addMethod(this.constructorBuilder.build())
                .addMethods(this.methods)
                .build();


        return Result.ofException(() -> JavaFile.builder(this.packageName, clazz)
                        .addFileComment("File was automatically generated by modolus processor")
                        .build()
                        .writeTo(processingEnvironment.getFiler()), IOException.class)
                .mapError(exception -> new ProcessorException(this.root, exception));
    }

}
