package dev.modolus.util.singleton;

public enum SingletonError {

    NO_INSTANCE_AVAILABLE,
    SINGLETON_ALREADY_PROVIDED,
    INSTANCE_IS_NOT_THE_REQUESTED_TYPE,
    VALUE_DOES_NOT_IMPLEMENT_SINGLETON_INTERFACE,
    FAILED_TO_GET_CALLERS_SCOPE,
    SCOPE_ALREADY_INITIALIZED

}
