/*
 * Copyright (C) 2026 Modolus-Framework
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package dev.modolus.processor;

import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeSpec;
import dev.modolus.util.result.Result;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Element;
import javax.lang.model.element.Modifier;
import lombok.Getter;
import org.jetbrains.annotations.NotNull;

public final class SourceFileWriter {

  @Getter private final TypeSpec.Builder classBuilder;

  private final Element root;
  private final String packageName;
  private final MethodSpec.Builder constructorBuilder;
  private final List<MethodSpec> methods;
  private final List<FieldSpec> fields;

  public SourceFileWriter(
      @NotNull Element root, @NotNull String packageName, @NotNull String className) {
    this.root = root;
    this.packageName = packageName;
    this.classBuilder = TypeSpec.classBuilder(className);
    this.constructorBuilder = MethodSpec.constructorBuilder().addModifiers(Modifier.PROTECTED);
    this.methods = new ArrayList<>();
    this.fields = new ArrayList<>();
  }

  public MethodSpec.Builder getConstructor() {
    return this.constructorBuilder;
  }

  public void addField(FieldSpec field) {
    this.fields.add(field);
  }

  public void addMethod(MethodSpec method) {
    this.methods.add(method);
  }

  public @NotNull Result<Void, ProcessorException> write(
      @NotNull ProcessingEnvironment processingEnvironment) {
    var clazz =
        classBuilder
            .addFields(this.fields)
            .addMethod(this.constructorBuilder.build())
            .addMethods(this.methods)
            .build();

    return Result.ofExceptionVoid(
            () ->
                JavaFile.builder(this.packageName, clazz)
                    .addFileComment("File was automatically generated by modolus processor")
                    .build()
                    .writeTo(processingEnvironment.getFiler()),
            IOException.class)
        .mapError(exception -> new ProcessorException(this.root, exception));
  }
}
